Update push hook

diff --git a/.hooks/pre-push b/.hooks/pre-push
--- a/.hooks/pre-push
+++ b/.hooks/pre-push
@@ -1,3 +1,24 @@
 #!/bin/sh
-cargo fmt --manifest-path chef-lang/Cargo.toml --check || exit 1
-cargo clippy --manifest-path chef-lang/Cargo.toml -- --deny warnings || exit 1
+
+manifest="chef-lang/Cargo.toml"
+
+cargo fmt --manifest-path "$manifest" --check 2> /dev/null  || {
+    echo -e "\nPlease format your code."
+    exit 1
+}
+
+echo "PASSED: Format"
+
+cargo clippy --manifest-path "$manifest" -- --deny warnings 2> /dev/null || {
+    echo -e "\nClippy is angry."
+    exit 1
+}
+
+echo "PASSED: Clippy"
+
+cargo test --manifest-path "$manifest" -q 2> /dev/null || {
+    echo -e "\nSome tests have failed"
+    exit 1
+}
+
+echo "PASSED: Tests"
